precommit hook improvement

diff --git a/conference/react-js/pre-commit b/conference/react-js/pre-commit
--- a/conference/react-js/pre-commit
+++ b/conference/react-js/pre-commit
@@ -1,33 +1,35 @@
 #!/bin/bash
+
+#move to our directory
 cd "$(git rev-parse --show-toplevel)"
-ESLINT="./conference/react-js/node_modules/.bin/eslint"
-pwd
+cd conference/react-js
 
-if [[ ! -x "$ESLINT" ]]; then
-  printf "\t\033[41mPlease install ESlint\033[0m (npm install eslint)\n"
-  exit 1
-fi
-
-STAGED_FILES=($(git diff --cached --name-only --diff-filter=ACM | grep ".jsx\{0,1\}$"))
-
-echo "ESLint'ing ${#STAGED_FILES[@]} files"
-
-if [[ "$STAGED_FILES" = "" ]]; then
-  exit 0
-fi
-
-$ESLINT "${STAGED_FILES[@]}" --fix
-
+#---------------------------------
+#ESLint
+echo ".....ESLint....."
+npm run lint
 ESLINT_EXIT="$?"
 
-# Re-add files since they may have been fixed
-git add "${STAGED_FILES[@]}"
-
 if [[ "${ESLINT_EXIT}" == 0 ]]; then
-  printf "\n\033[42mCOMMIT SUCCEEDED\033[0m\n"
+  printf "\n\033[42mESLINT SUCCEEDED\033[0m\n"
 else
-  printf "\n\033[41mCOMMIT FAILED:\033[0m Fix eslint errors and try again\n"
+  printf "\n\033[41mESLINT FAILED:\033[0m Fix eslint errors and try again\n"
+  exit 1
+fi
+#---------------------------------
+
+#---------------------------------
+#Tests
+echo ".....Unit tests....."
+npm run test
+TESTS_EXIT="$?"
+
+if [[ "${TESTS_EXIT}" == 0 ]]; then
+  printf "\n\033[42mTESTS SUCCEEDED\033[0m\n"
+else
+  printf "\n\033[41mTESTS FAILED:\033[0m Fix tests errors and try again\n"
   exit 1
 fi
 
+#---------------------------------
 exit $?
